Add Docker Setup
python-discord/forms-frontend pull request #258
Opened 2021-05-14 07:32 UTC by HassanAbouelela

Adds a docker file that builds the frontend, and a docker-compose which houses the backend and the frontend.

The main thing missing from these changes is that file reloading does not work. Webpack-dev-server by default enables the [webpack watch option](https://webpack.js.org/configuration/watch/), but for whatever reason, it doesn't work in the docker build. I've stumbled upon [this](https://stackoverflow.com/a/46844475) SO post multiple times in my search, but nothing I tried worked.

Ultimately, file watching is a QoL feature. I think not having it slows down development significantly, but I simply couldn't figure it out. It can be added in the future if someone figures it out, but for now I figure a semi-working setup is better than nothing.

2021-05-14 12:28 UTC, dawnofmidnight commented
I personally think that `docker-compose.yaml` should be renamed to `docker-compose.yml` to ensure consistency with the other repositories.

2021-05-14 13:13 UTC, dawnofmidnight approved these changes
Works fine for me

2021-07-25 20:50 UTC, Bluenix2 requested changes
> The main thing missing from these changes is that file reloading does not work. Webpack-dev-server by default enables the [webpack watch option](https://webpack.js.org/configuration/watch/), but for whatever reason, it doesn't work in the docker build. I've stumbled upon [this](https://stackoverflow.com/a/46844475) SO post multiple times in my search, but nothing I tried worked.
> 
> Ultimately, file watching is a QoL feature. I think not having it slows down development significantly, but I simply couldn't figure it out. It can be added in the future if someone figures it out, but for now I figure a semi-working setup is better than nothing.

As discussed in the Discord server, the following diff should be applied to make file watching work correctly:
```diff
diff --git a/webpack.config.js b/webpack.config.js
index 35c90a7..3c9b656 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -71,9 +71,14 @@ module.exports = {
     },
     devServer: {
         contentBase: path.join(__dirname, 'public'),
+        watchContentBase: true,
         compress: true,
         port: 3000,
         historyApiFallback: true,
+        watchOptions: {
+            aggregateTimeout: 500,
+            poll: 1000
+        },
     },
     plugins: [
     new CopyPlugin({
```
With this change I was able to test file watching correctly, we should also document how because of this `docker-compose` should not be used for deployment.

2022-01-30 06:04 UTC, HassanAbouelela commented on docker-compose.yaml
> +      - .env
Yes it was, I've added it in my last push.

2022-01-30 06:05 UTC, HassanAbouelela commented
@Bluenix2 I had tested the watch options extensively when I made this PR, but it did not seem to work for me. I tested it again now with the same result (I've ensured the modified file is copied correctly into the container). Perhaps this is an OS-dependent problem? What environment are you running in? If it works for some people, might as well leave it in, but it's broken for me.

Also, did you mean to put those options in devServer? watchContentBase is (perhaps no longer) documented, so this is what I've added at the top level:
```js
    watch: true,
    watchOptions: {
        aggregateTimeout: 500,
        poll: 1000,
    },
```

(P.S we don't need to document that it can't be used for production, that's already true of all our composes. We don't use compose in production)

2022-02-05 01:38 UTC, kosayoda approved these changes
File watching works without further modifications on my linux machine. Since it's not a necessary feature, we can move ahead with the PR.

Everything else works as expected 👍🏻

2022-02-05 01:38 UTC, kosayoda commented on docker-compose.yaml
> +      - /app/node_modules  # Ensure dependencies do not collide with a user's local install
This workaround requires at least an empty `node_modules` folder in the repo. I'll add that to the notion docs for now.

2022-02-05 01:43 UTC, jb3 approved these changes
approval thanks

2022-02-05 01:45 UTC, kosayoda commented on docker-compose.yaml
> +      - /app/node_modules  # Ensure dependencies do not collide with a user's local install
Docs added.

2022-02-05 01:45 UTC, merged